image: itxtech/docker-env-cenisys

variables:
  ZANATA_URL: https://translate.zanata.org/
  ZANATA_USERNAME: ishitatsuyuki

stages:
 - prepare
 - build
 - deploy

translation_download:
  stage: prepare
  script:
   - zanata-cli -B pull --create-skeletons
   - find src -name "*.cpp" | xgettext -ktranslate:1,1t -ktranslate:1,2,3t -C --boost -f- -o po/cenisys.pot --copyright-holder="iTX Technologies" --package-name=Cenisys
  cache:
    untracked: true
  artifacts:
    untracked: true
    paths:
     - po/ 
  only:
   - master

build:linux:
  stage: build
  script:
   - mkdir -p build
   - cd build
   - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DVERSION_SUFFIX=`[ -z "$CI_BUILD_TAG" ] && echo "$CI_BUILD_REF" || echo ""` ..
   - DESTDIR=.. ninja-build install
  cache:
    untracked: true
    paths:
     - build/
  artifacts:
    name: "cenisys-linux-$CI_BUILD_REF"
    paths:
     - usr/

zanata_upload:
  stage: deploy
  dependencies:
   - translation_download
  script:
   - zanata-cli -B push --url $ZANATA_URL --username $ZANATA_USERNAME --key $ZANATA_KEY
  only:
   - master

pages:
  stage: deploy
  dependencies:
   - build:linux
  script:
   - cp -r usr/share/doc/cenisys/html/ public
  artifacts:
    paths:
     - public/
  only:
   - master
