image: itxtech/docker-env-cenisys

variables:
  ZANATA_URL: https://translate.zanata.org/
  ZANATA_USERNAME: ishitatsuyuki

stages:
 - prepare
 - build
 - deploy

translation_download:
  stage: prepare
  script:
   - zanata-cli -B pull --create-skeletons
   - find src -name "*.cpp" | xgettext -ktranslate:1,1t -ktranslate:1,2,3t -C --boost -f- -o po/cenisys.pot --copyright-holder="iTX Technologies" --package-name=Cenisys
  cache:
    untracked: true
  artifacts:
    untracked: true
    paths:
     - po/ 
  only:
   - master
  allow_failure: true

build:gcc:
  stage: build
  script:
   - mkdir -p build
   - cd build
   - CC=gcc CXX=g++ cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DVERSION_SUFFIX=`[ -z "$CI_BUILD_TAG" ] && echo "${CI_BUILD_REF:0:7}" || echo ""` ..
   - DESTDIR=.. ninja-build install
  cache:
    untracked: true
    paths:
     - build/
  artifacts:
    name: "cenisys-gcc-${CI_BUILD_REF:0:7}"
    paths:
     - usr/

.build:clang:
  stage: build
  script:
   - mkdir -p build
   - cd build
   - CC=clang CXX=clang++ CFLAGS="-fprofile-arcs -ftest-coverage -flto" CXXFLAGS="-fprofile-arcs -ftest-coverage -flto" cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo DCMAKE_INSTALL_PREFIX=/usr -DBUILD_DOC=OFF -DVERSION_SUFFIX=`[ -z "$CI_BUILD_TAG" ] && echo "${CI_BUILD_REF:0:7}" || echo ""` ..
   - DESTDIR=.. ninja-build install
  cache:
    untracked: true
    paths:
     - build/
  artifacts:
    name: "cenisys-clang-debug-${CI_BUILD_REF:0:7}"
    paths:
     - usr/

clang-static:
  stage: build
  script:
   - mkdir -p build
   - cd build
   - scan-build cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DBUILD_DOC=OFF -DVERSION_SUFFIX=`[ -z "$CI_BUILD_TAG" ] && echo "${CI_BUILD_REF:0:7}" || echo ""` ..
   - ninja-build
  dependencies:
  cache:
    untracked: true
    paths:
     - build/
  allow_failure: true

zanata_upload:
  stage: deploy
  dependencies:
   - translation_download
  script:
   - zanata-cli -B push --url $ZANATA_URL --username $ZANATA_USERNAME --key $ZANATA_KEY
  only:
   - master
  allow_failure: true

pages:
  stage: deploy
  dependencies:
   - build:gcc
  script:
   - cp -r usr/share/doc/cenisys/html/ public
  artifacts:
    paths:
     - public/
  only:
   - master
