stages:
 - build
 
compile:
  image: itxtech/docker-env-cenisys
  stage: build
  script:
   - mkdir -p build
   - cd build
   - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../release ../
   - ninja install
  cache:
    key: "$CI_BUILD_NAME/$CI_BUILD_REF_NAME"
    paths:
     - build/
  artifacts:
    paths:
     - release/
